### ISSUE TITLE
example where some dependencies get hoisted

### ISSUE THREAD

**Issue by brysgo** [connectdotz/yarn-nohoist-examples#6]
Hey, thanks a lot for this, it has been really helpful!

I am looking for an example where some dependencies do get hoisted.

The trouble I am having is that when I call out react-native, expo, etc... to be hoisted, react native is having trouble finding the rest of my dependencies.

**Comment by connectdotz** [comment]
did you try [universal_cipher](https://github.com/connectdotz/yarn-nohoist-examples/tree/master/workspaces-examples/universal-cipher) example? if it is similar to #4, it should work now.

**Comment by brysgo** [comment]
Thanks @connectdotz I will try it out.

**Comment by trompx** [comment]
Hey @connectdotz,

I have a similar setup to publishing docker webpack. In root I installed webpack and webpack dev server.
I have multiples apps in packages folder where I set either the same webpack dev server version or a different one (the goad is to have a common version for all projects). Using yarn workspaces, the webpack dev server module is hoisted to the root.

Root package json:
```
"scripts": {
    "dev-app1": "cd packages/app1 && yarn dev",
},
```

App1 package json:
```
"scripts": {
    "dev": "NODE_ENV=development webpack-dev-server --mode development --env development",
},
```

So when running dev-app1 from root, I get `webpack-dev-server: not found`.

I guess you don't have that problem in your repo as just w2 app has webpack dependency and is installed in the w2/node_modules folder? Should i add webpack-dev-server to nohoist array? In that case I would not be able to have a common setup for multiple projects :(

Any ideas how to make this work?

**Comment by trompx** [comment]
I managed to make this work somehow.

I just forgot to mention that I am developping in a Vagrant VM with a Windows host, and it has its importance. In fact in order to install all node modules, I need to use `--no-bin-links`.

To run webpack-dev-server from CLI (in yarn scripts), I do:
`$ yarn node ./node_modules/lerna bootstrap`

So now I have in App1 package json:
```
"scripts": {
    "dev": "node ../../node_modules/webpack-dev-server --mode development",
},
```

One problem remains. Running `yarn run dev-app1` executes but exists immediatly once done, while I'd except the dev-server to keep running...

**Comment by connectdotz** [comment]
> Do you use lerna only for its publishing features or does it play a role in the symlinking of hoisted modules?

lerna is completely optional, I only used the `lerna run` to invoke scripts from each package since it determines the execution order automatically by their dependency relationship, which is nice. But of course you can use your own script.

lerna is not used for package installation/hoist/nohoist etc. [webpack-docker](https://github.com/connectdotz/yarn-nohoist-examples/tree/master/workspaces-examples/publishing/webpack-docker) is a plain yarn workspaces so to speak.
